### PR TITLE
Cleaned Star.cpp

### PR DESCRIPTION
**Pull request by ghost**
Made Star::draw easier to read

### CODE REVIEW

**Comment by ghost** [comment]
Just thought my changes made the code easier to read and shorter :)

**Comment by Jachdich** [comment]
Sorry can't approve this, it goes against some python shit about flat is better than nested even tho this isn't python, it is shit so it applies here I think but only on Wednesdays or Saturdays

**Comment by Jachdich** [comment]
Actually idk I'll see about it

**Comment by ghost** [comment]
Idk I think it is easier to understand what is going on imo, I think indentation is only issue if it gets too out of hand. If you think your formatting is better you don't have to change it.

**Pull request closed without merging**
